<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Listing;
use App\Models\User;

class DummyListingSeeder extends Seeder
{
    public function run()
    {
        $user = User::first(); // Assign to the first user (usually superadmin)
        if (!$user) {
            $user = User::create([
                'name' => 'Super Admin',
                'email' => 'admin@homefinder.com',
                'password' => bcrypt('password'),
                'role' => 'superadmin',
                'phone_number' => '081234567890'
            ]);
        }

        $properties = [
            // --- JAKARTA ---
            [
                'title' => 'Panorama Glass Residence',
                'location' => 'Kebayoran Baru, Jakarta Selatan',
                'city' => 'Jakarta Selatan',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 500,
                'price' => 18500000000,
                'price_formatted' => 'Rp 18,5 Milyar',
                'is_rent' => false,
                'badge' => 'FEATURED LUXURY',
                'image_url' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Rumah mewah dengan kaca panorama yang indah.',
            ],
            [
                'title' => 'Scandinavian Modern Penthouse',
                'location' => 'Menteng, Jakarta Pusat',
                'city' => 'Jakarta Pusat',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 320,
                'price' => 12000000000,
                'price_formatted' => 'Rp 12,0 Milyar',
                'is_rent' => false,
                'badge' => 'EXCLUSIVE',
                'image_url' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Apartemen',
                'status' => 'available',
                'description' => 'Penthouse modern dengan sentuhan skandinavian.',
            ],
            [
                'title' => 'Tropical Modern Resort House',
                'location' => 'Pondok Indah, Jakarta Selatan',
                'city' => 'Jakarta Selatan',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 620,
                'price' => 16500000000,
                'price_formatted' => 'Rp 16,5 Milyar',
                'is_rent' => false,
                'badge' => 'ELITE RESIDENCE',
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Rumah tropis modern layaknya resort mewah.',
            ],
            [
                'title' => 'Skyline Executive Apartment',
                'location' => 'SCBD, Jakarta Selatan',
                'city' => 'Jakarta Selatan',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 180,
                'price' => 35000000,
                'price_formatted' => 'Rp 35 Juta /bulan',
                'is_rent' => true,
                'badge' => 'SEWA PENTHOUSE',
                'image_url' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Apartemen',
                'status' => 'available',
                'description' => 'Apartemen eksekutif dengan pemandangan skyline.',
            ],
            [
                'title' => 'PIK Coastal Golf Residence',
                'location' => 'Pantai Indah Kapuk (PIK 2), Jakarta Utara',
                'city' => 'Jakarta Utara',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area' => 450,
                'price' => 22500000000,
                'price_formatted' => 'Rp 22,5 Milyar',
                'is_rent' => false,
                'badge' => 'WATERFRONT',
                'image_url' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Hunian pesisir dengan pemandangan lapangan golf.',
            ],
            [
                'title' => 'Minimalist Urban Studio Loft',
                'location' => 'Cipete, Jakarta Selatan',
                'city' => 'Jakarta Selatan',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 95,
                'price' => 15000000,
                'price_formatted' => 'Rp 15 Juta /bulan',
                'is_rent' => true,
                'badge' => 'SEWA STUDIO',
                'image_url' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Apartemen',
                'status' => 'available',
                'description' => 'Studio minimalis yang nyaman di pusat kota.',
            ],
            [
                'title' => 'Puri Botanical Garden Villa',
                'location' => 'Puri Indah, Jakarta Barat',
                'city' => 'Jakarta Barat',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 290,
                'price' => 8500000000,
                'price_formatted' => 'Rp 8,5 Milyar',
                'is_rent' => false,
                'badge' => 'GREEN LIVING',
                'image_url' => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Villa dengan taman botani yang asri.',
            ],

            // --- BALI ---
            [
                'title' => 'Ocean front Luxury Villa',
                'location' => 'Seminyak, Bali',
                'city' => 'Bali',
                'bedrooms' => 5,
                'bathrooms' => 3,
                'area' => 750,
                'price' => 24000000000,
                'price_formatted' => 'Rp 24,0 Milyar',
                'is_rent' => false,
                'badge' => 'BEACHFRONT',
                'image_url' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Villa mewah dengan akses langsung ke pantai.',
            ],
            [
                'title' => 'Cliff top Infinity Villa',
                'location' => 'Uluwatu, Bali',
                'city' => 'Bali',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area' => 800,
                'price' => 45000000,
                'price_formatted' => 'Rp 45 Juta /bulan',
                'is_rent' => true,
                'badge' => 'SEWA EKSKLUSIF',
                'image_url' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Villa di atas tebing dengan pemandangan tanpa batas.',
            ],
            [
                'title' => 'Canggu Eco Jungle Sanctuary',
                'location' => 'Canggu, Bali',
                'city' => 'Bali',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area' => 420,
                'price' => 14800000000,
                'price_formatted' => 'Rp 14,8 Milyar',
                'is_rent' => false,
                'badge' => 'TROPICAL PARADISE',
                'image_url' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Tempat peristirahatan bernuansa hutan yang ekologis.',
            ],
            [
                'title' => 'Ubud Riverview Ricefield Villa',
                'location' => 'Ubud, Bali',
                'city' => 'Bali',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 310,
                'price' => 28000000,
                'price_formatted' => 'Rp 28 Juta /bulan',
                'is_rent' => true,
                'badge' => 'SEWA VILLA',
                'image_url' => 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Villa dengan pemandangan sungai dan sawah.',
            ],

            // --- TANGERANG & TANGSEL ---
            [
                'title' => 'Botanical Garden Haven',
                'location' => 'BSD City, Tangerang Selatan',
                'city' => 'Tangerang Selatan',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 410,
                'price' => 9800000000,
                'price_formatted' => 'Rp 9,8 Milyar',
                'is_rent' => false,
                'badge' => 'HOT & NEW',
                'image_url' => 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Rumah bernuansa kebun botani yang nyaman.',
            ],
            [
                'title' => 'Verdant Green Park Residence',
                'location' => 'Alam Sutera, Tangerang',
                'city' => 'Tangerang Selatan',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 380,
                'price' => 7200000000,
                'price_formatted' => 'Rp 7,2 Milyar',
                'is_rent' => false,
                'badge' => 'BEST SELLER',
                'image_url' => 'https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Hunian hijau di lingkungan taman asri.',
            ],
            [
                'title' => 'Bintaro Smart Family Home',
                'location' => 'Bintaro Jaya Sektor 9, Tangerang Selatan',
                'city' => 'Tangerang Selatan',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 250,
                'price' => 4500000000,
                'price_formatted' => 'Rp 4,5 Milyar',
                'is_rent' => false,
                'badge' => 'SMART HOME',
                'image_url' => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Rumah pintar ramah keluarga di Bintaro.',
            ],

            // --- BANDUNG ---
            [
                'title' => 'Dago Highland Heritage Villa',
                'location' => 'Dago Pakar, Bandung',
                'city' => 'Bandung',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area' => 600,
                'price' => 11500000000,
                'price_formatted' => 'Rp 11,5 Milyar',
                'is_rent' => false,
                'badge' => 'MOUNTAIN VIEW',
                'image_url' => 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Villa klasik dengan pemandangan pegunungan Dago.',
            ],
            [
                'title' => 'Setiabudi Pine Forest Residence',
                'location' => 'Setiabudi, Bandung',
                'city' => 'Bandung',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 310,
                'price' => 18000000,
                'price_formatted' => 'Rp 18 Juta /bulan',
                'is_rent' => true,
                'badge' => 'SEWA SEHAT',
                'image_url' => 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Hunian sejuk dikelilingi hutan pinus Setiabudi.',
            ],

            // --- SURABAYA ---
            [
                'title' => 'Surabaya Pakuwon Golf Estate',
                'location' => 'Pakuwon Indah, Surabaya Barat',
                'city' => 'Surabaya',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 520,
                'price' => 15200000000,
                'price_formatted' => 'Rp 15,2 Milyar',
                'is_rent' => false,
                'badge' => 'SURABAYA ELITE',
                'image_url' => 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Rumah prestisius di kawasan golf Pakuwon.',
            ],
            [
                'title' => 'Citraland Grand Residence',
                'location' => 'Citraland, Surabaya',
                'city' => 'Surabaya',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 340,
                'price' => 6900000000,
                'price_formatted' => 'Rp 6,9 Milyar',
                'is_rent' => false,
                'badge' => 'FAMILY CHOICE',
                'image_url' => 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Residensial',
                'status' => 'available',
                'description' => 'Hunian nyaman bernuansa resort untuk keluarga Anda.',
            ],

            // --- YOGYAKARTA ---
            [
                'title' => 'Malioboro Heritage Residence',
                'location' => 'Sleman, Yogyakarta',
                'city' => 'Yogyakarta',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 280,
                'price' => 3800000000,
                'price_formatted' => 'Rp 3,8 Milyar',
                'is_rent' => false,
                'badge' => 'CULTURAL LUXURY',
                'image_url' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Hunian dengan arsitektur klasik Jawa.',
            ],

            // --- BOGOR & BEKASI ---
            [
                'title' => 'Sentul City Hills Villa',
                'location' => 'Sentul City, Bogor',
                'city' => 'Bogor',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 400,
                'price' => 5400000000,
                'price_formatted' => 'Rp 5,4 Milyar',
                'is_rent' => false,
                'badge' => 'COOL BREEZE',
                'image_url' => 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Villa di perbukitan dengan angin sejuk.',
            ],
            [
                'title' => 'Summarecon Bekasi Modern Loft',
                'location' => 'Summarecon, Bekasi',
                'city' => 'Bekasi',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 160,
                'price' => 2800000000,
                'price_formatted' => 'Rp 2,8 Milyar',
                'is_rent' => false,
                'badge' => 'URBAN APARTMENT',
                'image_url' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Apartemen',
                'status' => 'available',
                'description' => 'Apartemen loft bergaya urban di Summarecon Bekasi.',
            ],

            // --- MEDAN & MAKASSAR ---
            [
                'title' => 'Medan Setiabudi Mansion',
                'location' => 'Setiabudi, Medan',
                'city' => 'Medan',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 390,
                'price' => 4900000000,
                'price_formatted' => 'Rp 4,9 Milyar',
                'is_rent' => false,
                'badge' => 'SUMATRA PRIME',
                'image_url' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Rumah',
                'status' => 'available',
                'description' => 'Mansion mewah di kawasan Setiabudi Medan.',
            ],
            [
                'title' => 'Losari Waterfront Apartment',
                'location' => 'Pantai Losari, Makassar',
                'city' => 'Makassar',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area' => 140,
                'price' => 20000000,
                'price_formatted' => 'Rp 20 Juta /bulan',
                'is_rent' => true,
                'badge' => 'SEWA OCEANVIEW',
                'image_url' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
                'category' => 'Apartemen',
                'status' => 'available',
                'description' => 'Apartemen dengan view laut dan sunset Losari yang memukau.',
            ],
        ];

        foreach ($properties as $prop) {
            $prop['user_id'] = $user->id;
            
            // Dummy features
            $features = [
                'Keamanan 24 Jam', 
                'Kolam Renang Privat', 
                'Smart Home System',
                'Carport Luas',
                'Clubhouse Eksklusif'
            ];
            
            if ($prop['is_rent']) {
                $features = ['Keamanan 24 Jam', 'Akses Gym & Spa', 'Full Furnished'];
            }
            
            $prop['features'] = json_encode($features);
            
            Listing::create($prop);
        }
    }
}
